#!/bin/bash

set -e

if [ $# -eq 0 ]; then
	echo "Please specify new package path"
	exit
fi

NEW_DPKG="$1"

expect() {
	local old="$1"
	local op="$2"
	local new="$3"

	if [ "$old" $op "$new" ]; then
		echo "OK: $old $op $new"
	else
		echo "FAILURE: $old ! $op $new"
		exit 1
	fi
}

getver() { porto -v 2>&1 | grep server | awk '{print $2}'; }

check_state() {
	expect "$(porto list -1 | tr -d ' ')" = "$(echo -e 'a\na/b\nx\ny\nz\n')"

	expect "$(porto get x command)" = "sleep 1000"
	expect "$(porto get x isolate)" = "false"
	expect "$(porto get x state)" = "running"

	expect "$(porto get y command)" = "false"
	expect "$(porto get y isolate)" = "true"
	expect "$(porto get y state)" = "dead"
	expect "$(porto dget y exit_status)" = "256"

	expect "$(porto get z command)" = "sleep 3000"
	expect "$(porto get z isolate)" = "true"
	expect "$(porto get z state)" = "stopped"

        # current stable version (1.9) reports invalid state
        # for meta containers; uncomment when stable is 1.16
        #expect "$(porto get a state)" = "meta"

	expect "$(porto get a/b command)" = "sleep 4000"
	expect "$(porto get a/b state)" = "running"
}

cleanup_tc() {
	for link in $(ip -o link | awk -F: '{print $2}'); do
		tc filter del dev $link pref 10 || :
	done
}

wait_porto() {
        echo "Waiting porto startup..."
        # versions prior to 1.17 don't return error when porto
        # can't connect to socket, just sleep here
        sleep 10

#       for i in `seq 60`; do
#               if porto list; then
#                       return
#               fi
#
#               sleep 1
#       done
#
#       echo "Porto is dead, don't continue"
#       exit 1
}

cleanup_tc
sudo apt-get install -y --force-yes yandex-porto/stable
sudo restart yandex-porto
wait_porto
oldver="$(getver)"

porto run x command='sleep 1000' isolate=false
porto run y command='false'
sleep 1 # wait y exit

porto create z
porto set z command sleep 3000

porto create a
porto create a/b
porto set a/b command sleep 4000
porto start a/b

check_state

cleanup_tc
sudo dpkg -i "$NEW_DPKG"
wait_porto
newver="$(getver)"

expect "$oldver" != "$newver"

check_state

porto destroy a x y z
